/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaosw_library_jni_TestJni */

#ifndef _Included_com_xiaosw_library_jni_TestJni
#define _Included_com_xiaosw_library_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaosw_library_jni_TestJni
 * Method:    test
 * Signature: (ILjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_xiaosw_library_jni_TestJni_test
  (JNIEnv *, jobject, jint, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
